import type { FastifyPluginAsync } from 'fastify';
import { AttentionActionSchema } from '@scott-ops/shared/schemas';

// /api/attention/* — read + lifecycle for Attention Engine items (Addendum
// 05). The items are generated by the daily cron (see lib/attention.ts); this
// route surfaces them and applies snooze / dismiss / acted-on / reactivate.

export const attentionRoutes: FastifyPluginAsync = async (app) => {
  app.addHook('preHandler', app.requireAuth);

  // List — defaults to active, highest score first. Pass status=snoozed etc.
  // to inspect other buckets, or all=true for everything.
  app.get<{ Querystring: { status?: string; urgency?: string; limit?: string; all?: string } }>(
    '/api/attention',
    async (req) => {
      const limit = Math.min(parseInt(req.query.limit ?? '200', 10) || 200, 500);
      let q = req.supabase!
        .from('attention_items')
        .select('*')
        .order('score', { ascending: false })
        .order('last_surfaced_at', { ascending: false })
        .limit(limit);
      if (req.query.all !== 'true') {
        q = q.eq('status', req.query.status ?? 'active');
      } else if (req.query.status) {
        q = q.eq('status', req.query.status);
      }
      if (req.query.urgency) q = q.eq('urgency', req.query.urgency);
      const { data, error } = await q;
      if (error) throw app.httpErrors.internalServerError(error.message);
      return { items: data ?? [] };
    },
  );

  // Count of active items — cheap, for the nav badge.
  app.get('/api/attention/count', async (req) => {
    const { count, error } = await req.supabase!
      .from('attention_items')
      .select('id', { count: 'exact', head: true })
      .eq('status', 'active');
    if (error) throw app.httpErrors.internalServerError(error.message);
    return { active: count ?? 0 };
  });

  // Apply a lifecycle action.
  app.patch<{ Params: { id: string } }>('/api/attention/:id', async (req, reply) => {
    const parsed = AttentionActionSchema.safeParse(req.body);
    if (!parsed.success) {
      return reply.code(400).send({ error: 'invalid_payload', details: parsed.error.flatten() });
    }
    const now = new Date().toISOString();
    let update: Record<string, unknown>;
    switch (parsed.data.action) {
      case 'snooze': {
        const until =
          parsed.data.until ??
          new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10);
        update = { status: 'snoozed', snoozed_until: until };
        break;
      }
      case 'dismiss':
        update = { status: 'dismissed', dismissed_at: now };
        break;
      case 'acted_on':
        update = {
          status: 'acted_on',
          acted_on_at: now,
          acted_on_action: parsed.data.acted_on_action ?? null,
        };
        break;
      case 'reactivate':
        update = { status: 'active', snoozed_until: null, dismissed_at: null, last_surfaced_at: now };
        break;
    }
    const { data, error } = await req.supabase!
      .from('attention_items')
      .update(update)
      .eq('id', req.params.id)
      .select('*')
      .single();
    if (error) throw app.httpErrors.internalServerError(error.message);
    return data;
  });
};
